# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    weird_authenticator:
        class: AppBundle\Security\WeirdFormAuthenticator
        # arguments: ['@doctrine.orm.entity_manager', '@router']
        autowire: true

    user_voter:
        class: AppBundle\Security\UserVoter
        autowire: true
        tags:
            - { name: security.voter }
